# Generated by Django 3.1.3 on 2020-11-07 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='worker',
        ),
        migrations.CreateModel(
            name='Сonnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.animal')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.worker')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='zoo_animals',
            field=models.ManyToManyField(through='animal.Сonnection', to='animal.Animal'),
        ),
    ]
